# Generated by Django 4.2.7 on 2023-11-28 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='country_residence',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='phone_country',
            new_name='phone_number',
        ),
    ]
