# Generated by Django 4.2.7 on 2023-12-05 00:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(max_length=100)),
                ('icon', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ReservationCart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, null=True, unique=True)),
                ('adults', models.IntegerField(default=0, null=True)),
                ('children', models.IntegerField(default=0, null=True)),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('nights', models.IntegerField(null=True)),
                ('reservation_price', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('taxes', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('number', models.IntegerField()),
                ('building', models.IntegerField(default=1)),
                ('avaliability', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('room_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('type', models.CharField(max_length=255, unique=True)),
                ('short_description', models.TextField(blank=True, null=True)),
                ('description', models.TextField()),
                ('max_adults', models.IntegerField(blank=True, null=True)),
                ('max_children', models.IntegerField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='RoomReservations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('adults', models.IntegerField()),
                ('children', models.IntegerField()),
                ('total_price', models.IntegerField()),
                ('check_in_date', models.DateField(null=True)),
                ('check_out_date', models.DateField(null=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_reserved', to='booking.reservationcart')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.room')),
            ],
        ),
        migrations.CreateModel(
            name='RoomFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_types', to='booking.feature')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='booking.roomtype')),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_type', to='booking.roomtype'),
        ),
        migrations.AddField(
            model_name='reservationcart',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.room'),
        ),
        migrations.AddField(
            model_name='reservationcart',
            name='room_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.roomtype'),
        ),
        migrations.AddField(
            model_name='reservationcart',
            name='user',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('image', models.ImageField(blank=True, upload_to='rooms/')),
                ('alt', models.CharField(max_length=255)),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='booking.roomtype')),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('country', models.CharField(max_length=255)),
                ('postal_code', models.CharField(max_length=20)),
                ('card_number', models.CharField(max_length=16)),
                ('expire_date', models.CharField(max_length=7)),
                ('csv', models.CharField(max_length=4)),
                ('user_cart', models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guest', to='booking.reservationcart')),
            ],
        ),
    ]
