# Generated by Django 4.2.7 on 2023-11-29 19:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('image', models.ImageField(upload_to='rooms/')),
                ('alt', models.CharField(max_length=255)),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room', to='booking.roomtype')),
            ],
        ),
    ]
