# Generated by Django 4.2.7 on 2023-12-08 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='avaliability',
        ),
        migrations.RemoveField(
            model_name='room',
            name='building',
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('reservation_id', models.AutoField(primary_key=True, serialize=False)),
                ('reservation_confirmation_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('unique_identifier', models.CharField(max_length=70, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('adults', models.IntegerField(default=0, null=True)),
                ('children', models.IntegerField(default=0, null=True)),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('nights', models.IntegerField(null=True)),
                ('reservation_price', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('taxes', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.room')),
                ('room_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.roomtype')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='guest',
            name='user_cart',
            field=models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guest', to='booking.reservation'),
        ),
        migrations.AlterField(
            model_name='roomreservations',
            name='reservation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.reservation'),
        ),
        migrations.DeleteModel(
            name='ReservationCart',
        ),
    ]
