# Generated by Django 4.2.7 on 2023-12-09 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='avaliability',
        ),
        migrations.RemoveField(
            model_name='room',
            name='building',
        ),
        migrations.RemoveField(
            model_name='room',
            name='uuid',
        ),
    ]
