# Generated by Django 4.2.7 on 2023-12-01 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomreserved',
            name='check_in_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='roomreserved',
            name='check_out_date',
            field=models.DateField(null=True),
        ),
    ]
