# Generated by Django 4.2.7 on 2023-12-02 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_roomreserved_check_in_date_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RoomReserved',
            new_name='RoomReservations',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='avaibility',
            new_name='avaliability',
        ),
    ]
