# Generated by Django 4.2.7 on 2023-12-08 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_remove_room_avaliability_remove_room_building_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guest',
            old_name='user_cart',
            new_name='user_reservation',
        ),
    ]
