# Generated by Django 4.2.7 on 2023-12-02 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_roomtype_has_ac_roomtype_has_balcony_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomtype',
            old_name='has_ac',
            new_name='has_AC',
        ),
        migrations.RenameField(
            model_name='roomtype',
            old_name='has_tv',
            new_name='has_Tv',
        ),
        migrations.RenameField(
            model_name='roomtype',
            old_name='has_wifi',
            new_name='has_Wifi',
        ),
        migrations.RenameField(
            model_name='roomtype',
            old_name='has_cafeAndTeaSet',
            new_name='has_cafe_and_tea_set',
        ),
        migrations.RenameField(
            model_name='roomtype',
            old_name='has_doublebed',
            new_name='has_double_bed',
        ),
        migrations.AddField(
            model_name='roomtype',
            name='has_air_dryer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='has_bathrobe',
            field=models.BooleanField(default=False),
        ),
    ]
