# Generated by Django 4.2.7 on 2023-12-02 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_rename_has_ac_roomtype_has_ac_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomtype',
            old_name='has_Tv',
            new_name='has_TV',
        ),
    ]
