# Generated by Django 4.2.7 on 2023-12-02 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_reservationcart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='space_taken',
            field=models.BooleanField(default=False),
        ),
    ]
