# Generated by Django 4.2.7 on 2023-12-02 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_rename_has_tv_roomtype_has_tv'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='has_ceiling_ventilator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='has_sofa_bed',
            field=models.BooleanField(default=False),
        ),
    ]
