# Generated by Django 4.2.7 on 2023-12-10 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_guest_country_guest_postal_code_alter_guest_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='card_brand',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='card_last4',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='card_payment_token',
        ),
        migrations.AddField(
            model_name='guest',
            name='card_number',
            field=models.CharField(default=' ', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='csv',
            field=models.CharField(default=' ', max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guest',
            name='expire_date',
            field=models.CharField(default=' ', max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='country',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='guest',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='postal_code',
            field=models.CharField(default=' ', max_length=20),
            preserve_default=False,
        ),
    ]
