# Generated by Django 4.2.7 on 2023-12-10 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_remove_reservation_card_brand_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='card_number',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='csv',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='expire_date',
        ),
        migrations.AddField(
            model_name='reservation',
            name='card_brand',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='card_last4',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='card_payment_token',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='country',
            field=models.CharField(default='US', max_length=2),
        ),
        migrations.AlterField(
            model_name='guest',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='guest',
            name='postal_code',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
