# Generated by Django 4.2.7 on 2023-11-29 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_image_room_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='booking.roomtype'),
        ),
    ]
