# Generated by Django 4.2.7 on 2023-12-02 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_roomtype_has_ceiling_ventilator_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(max_length=100)),
                ('icon', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='roomtype',
            name='has_AC',
        ),
        migrations.RemoveField(
            model_name='roomtype',
            name='has_TV',
        ),
        migrations.RemoveField(
            model_name='roomtype',
            name='has_Wifi',
        ),
        migrations.RemoveField(
            model_name='roomtype',
            name='has_air_dryer',
        ),
        migrations.RemoveField(
            model_name='roomtype',
            name='has_balcony',
        ),
        migrations.RemoveField(
            model_name='roomtype',
            name='has_bathrobe',
        ),
        migrations.RemoveField(
            model_name='roomtype',
            name='has_cafe_and_tea_set',
        ),
        migrations.RemoveField(
            model_name='roomtype',
            name='has_ceiling_ventilator',
        ),
        migrations.RemoveField(
            model_name='roomtype',
            name='has_double_bed',
        ),
        migrations.RemoveField(
            model_name='roomtype',
            name='has_jacuzzi',
        ),
        migrations.RemoveField(
            model_name='roomtype',
            name='has_minibar',
        ),
        migrations.RemoveField(
            model_name='roomtype',
            name='has_safe',
        ),
        migrations.RemoveField(
            model_name='roomtype',
            name='has_shower',
        ),
        migrations.RemoveField(
            model_name='roomtype',
            name='has_sofa_bed',
        ),
    ]
