# Generated by Django 4.2.7 on 2023-12-02 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_room_space_taken'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationcart',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.room'),
        ),
    ]
