# Generated by Django 4.2.7 on 2023-12-10 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_remove_guest_card_number_remove_guest_csv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='unique_identifier',
            field=models.CharField(max_length=70, null=True, unique=True),
        ),
    ]
