# Generated by Django 4.2.7 on 2023-11-29 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_alter_image_room_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='short_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
