# Generated by Django 4.2.7 on 2023-12-02 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_reservationcart_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='space_taken',
        ),
        migrations.AddField(
            model_name='reservationcart',
            name='room_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.roomtype'),
        ),
    ]
