# Generated by Django 4.2.7 on 2023-11-29 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_roomtype_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='max_adults',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='min_adults',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
