# Generated by Django 4.2.7 on 2023-12-02 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_remove_room_space_taken_reservationcart_room_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('postal_code', models.CharField(max_length=20)),
                ('card_number', models.CharField(max_length=16)),
                ('expire_date', models.CharField(max_length=7)),
                ('csv', models.CharField(max_length=4)),
            ],
        ),
        migrations.AddField(
            model_name='reservationcart',
            name='nights',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='reservationcart',
            name='reservation_price',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='reservationcart',
            name='taxes',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='reservationcart',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
    ]
