# Generated by Django 4.2.7 on 2023-12-02 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_roomfeature'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='icon_class',
            field=models.CharField(default='', max_length=20),
        ),
    ]
