# Generated by Django 4.2.7 on 2023-12-03 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_guest_reservationcart_nights_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationcart',
            name='adults',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='reservationcart',
            name='children',
            field=models.IntegerField(null=True),
        ),
    ]
