# Generated by Django 4.2.7 on 2023-12-02 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_feature_icon_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='feature',
        ),
        migrations.AddField(
            model_name='feature',
            name='icon_2',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='feature',
            name='icon',
            field=models.CharField(max_length=100),
        ),
    ]
