# Generated by Django 4.2.7 on 2023-12-02 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_remove_feature_feature_feature_icon_2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feature',
            old_name='icon',
            new_name='feature',
        ),
    ]
