# Generated by Django 4.2.7 on 2023-12-02 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_rename_icon_feature_feature'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feature',
            old_name='feature',
            new_name='icon',
        ),
    ]
