# Generated by Django 4.2.7 on 2023-12-03 15:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_alter_reservationcart_adults_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationcart',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
    ]
