# Generated by Django 4.2.7 on 2023-12-02 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_rename_feature_feature_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='icon_2',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='icon_class',
        ),
    ]
