# Generated by Django 4.2.7 on 2023-12-02 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_remove_feature_icon_2_remove_feature_icon_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='feature',
            field=models.CharField(default='', max_length=100),
        ),
    ]
