# Generated by Django 4.2.7 on 2023-12-02 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_alter_feature_feature_alter_feature_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='feature',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='feature',
            name='icon',
            field=models.CharField(max_length=100),
        ),
    ]
