# Generated by Django 4.2.7 on 2023-12-02 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0018_rename_icona_feature_feature'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feature',
            old_name='icon',
            new_name='image',
        ),
    ]
