# Generated by Django 4.2.7 on 2023-12-02 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0019_rename_icon_feature_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feature',
            old_name='image',
            new_name='icon',
        ),
    ]
