# Generated by Django 4.2.7 on 2023-12-02 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0020_rename_image_feature_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feature',
            old_name='icon',
            new_name='icona',
        ),
    ]
