# Generated by Django 4.2.7 on 2023-12-02 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0022_rename_feature_feature_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feature',
            old_name='icona',
            new_name='feature',
        ),
    ]
