# Generated by Django 4.2.7 on 2023-12-02 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0024_alter_feature_feature_alter_feature_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='second_icon',
            field=models.CharField(default='', max_length=100),
        ),
    ]
