# Generated by Django 4.2.7 on 2023-12-02 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0026_remove_feature_second_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomfeature',
            name='feature',
        ),
        migrations.RemoveField(
            model_name='roomfeature',
            name='room_type',
        ),
        migrations.DeleteModel(
            name='Feature',
        ),
        migrations.DeleteModel(
            name='RoomFeature',
        ),
    ]
