# Generated by Django 4.2.7 on 2023-12-03 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='end_date',
            field=models.DateField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='start_date',
            field=models.DateField(default='', null=True),
        ),
    ]
