# Generated by Django 4.2.7 on 2023-12-03 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_report_end_date_alter_report_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
