# Generated by Django 4.2.7 on 2023-12-03 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_report_end_date_alter_report_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='end_date',
        ),
    ]
