# Generated by Django 4.2.7 on 2023-12-03 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_remove_report_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='end_date',
            field=models.DateField(null=True),
        ),
    ]
